# docker compose file for setting up NextCloud on Azure Apps

version: "3.9"

services:
  nextcloud:
    image: nextcloud:latest
    # container_name: nextcloud
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS="<appname>.azurewebsites.net"
    # restart: always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    # container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    # restart: always

volumes:
  nextcloud:
  db:
