version: "3.9"

services:
  nextcloud:
    image: nextcloud:latest
    # container_name: nextcloud
    ports:
      - '8080:80'

  mariadb:
    image: mariadb:latest
    # container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
  
  collabora:
    image: collabora/code
    # container_name: collabora
